# Generated by Django 5.2.1 on 2025-05-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ingredientdelivery_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealserving',
            name='possible_portions_at_serving',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
