# Generated by Django 5.2.1 on 2025-05-20 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mealserving_possible_portions_at_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='current_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
