# Generated by Django 5.2.1 on 2025-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ingredient_current_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
